[2023-10-01 06:15:28,562] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.second_task 2021-11-01T00:00:00+00:00 [queued]>
[2023-10-01 06:15:28,701] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.second_task 2021-11-01T00:00:00+00:00 [queued]>
[2023-10-01 06:15:28,734] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:15:28,748] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:15:28,756] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:15:29,182] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2021-11-01T00:00:00+00:00
[2023-10-01 06:15:29,427] {standard_task_runner.py:52} INFO - Started process 5370 to run task
[2023-10-01 06:15:29,678] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_fourth_dag_v4', 'second_task', '2021-11-01T00:00:00+00:00', '--job-id', '720', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_fourth_dag.py', '--cfg-path', '/tmp/tmpom8_q_yl', '--error-file', '/tmp/tmpq3eduh97']
[2023-10-01 06:15:29,922] {standard_task_runner.py:77} INFO - Job 720: Subtask second_task
[2023-10-01 06:15:31,661] {logging_mixin.py:104} INFO - Running <TaskInstance: our_fourth_dag_v4.second_task 2021-11-01T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:15:32,392] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_fourth_dag_v4
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-01T00:00:00+00:00
[2023-10-01 06:15:32,417] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:15:32,457] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2023-10-01 06:15:32,639] {bash.py:169} INFO - Output:
[2023-10-01 06:15:32,873] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2023-10-01 06:15:32,879] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:15:33,086] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_fourth_dag_v4, task_id=second_task, execution_date=20211101T000000, start_date=20231001T061528, end_date=20231001T061533
[2023-10-01 06:15:33,645] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01 06:15:33,941] {local_task_job.py:146} INFO - Task exited with return code 0
