[2023-10-01 06:16:01,923] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.first_task 2021-11-14T00:00:00+00:00 [queued]>
[2023-10-01 06:16:02,098] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.first_task 2021-11-14T00:00:00+00:00 [queued]>
[2023-10-01 06:16:02,103] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:16:02,105] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:16:02,110] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:16:02,248] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): first_task> on 2021-11-14T00:00:00+00:00
[2023-10-01 06:16:02,310] {standard_task_runner.py:52} INFO - Started process 5501 to run task
[2023-10-01 06:16:02,433] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_fourth_dag_v4', 'first_task', '2021-11-14T00:00:00+00:00', '--job-id', '747', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_fourth_dag.py', '--cfg-path', '/tmp/tmpr8jfz44h', '--error-file', '/tmp/tmpz23nquao']
[2023-10-01 06:16:02,487] {standard_task_runner.py:77} INFO - Job 747: Subtask first_task
[2023-10-01 06:16:03,344] {logging_mixin.py:104} INFO - Running <TaskInstance: our_fourth_dag_v4.first_task 2021-11-14T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:16:05,285] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_fourth_dag_v4
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2021-11-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-14T00:00:00+00:00
[2023-10-01 06:16:05,291] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:16:05,310] {bash.py:158} INFO - Running command: echo hello world, this is the first task!
[2023-10-01 06:16:05,571] {bash.py:169} INFO - Output:
[2023-10-01 06:16:05,632] {bash.py:173} INFO - hello world, this is the first task!
[2023-10-01 06:16:05,642] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:16:05,865] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_fourth_dag_v4, task_id=first_task, execution_date=20211114T000000, start_date=20231001T061601, end_date=20231001T061605
[2023-10-01 06:16:13,818] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 06:16:13,991] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 5501
[2023-10-01 06:16:14,848] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 06:16:14,852] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-10-01 06:16:16,966] {process_utils.py:66} INFO - Process psutil.Process(pid=5501, status='terminated', exitcode=1, started='06:16:02') (5501) terminated with exit code 1
