[2023-10-01 04:56:53,203] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.thrid_task 2021-08-05T00:00:00+00:00 [queued]>
[2023-10-01 04:56:54,713] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.thrid_task 2021-08-05T00:00:00+00:00 [queued]>
[2023-10-01 04:56:54,764] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 04:56:54,767] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 04:56:54,829] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 04:56:55,808] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): thrid_task> on 2021-08-05T00:00:00+00:00
[2023-10-01 04:56:56,045] {standard_task_runner.py:52} INFO - Started process 628 to run task
[2023-10-01 04:56:56,610] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v5', 'thrid_task', '2021-08-05T00:00:00+00:00', '--job-id', '15', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpaqemcmzq', '--error-file', '/tmp/tmp68v7cw2n']
[2023-10-01 04:57:03,079] {standard_task_runner.py:77} INFO - Job 15: Subtask thrid_task
[2023-10-01 04:57:19,091] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v5.thrid_task 2021-08-05T00:00:00+00:00 [running]> on host c25e1f8124bc
[2023-10-01 04:57:27,960] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=thrid_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-05T00:00:00+00:00
[2023-10-01 04:57:27,990] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 04:57:28,048] {bash.py:158} INFO - Running command: echo hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 04:57:29,770] {bash.py:169} INFO - Output:
[2023-10-01 04:57:30,042] {bash.py:173} INFO - hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 04:57:30,156] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 04:57:34,495] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=thrid_task, execution_date=20210805T000000, start_date=20231001T045653, end_date=20231001T045734
[2023-10-01 04:57:43,272] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 04:57:43,460] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 628
[2023-10-01 04:57:43,740] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 04:57:43,750] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-10-01 04:57:45,208] {process_utils.py:66} INFO - Process psutil.Process(pid=628, status='terminated', exitcode=1, started='04:56:55') (628) terminated with exit code 1
