[2023-10-01 06:12:57,940] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.thrid_task 2021-10-05T00:00:00+00:00 [queued]>
[2023-10-01 06:12:59,989] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.thrid_task 2021-10-05T00:00:00+00:00 [queued]>
[2023-10-01 06:12:59,990] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:12:59,992] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:12:59,996] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:13:00,505] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): thrid_task> on 2021-10-05T00:00:00+00:00
[2023-10-01 06:13:00,808] {standard_task_runner.py:52} INFO - Started process 4928 to run task
[2023-10-01 06:13:01,012] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_fourth_dag_v4', 'thrid_task', '2021-10-05T00:00:00+00:00', '--job-id', '637', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_fourth_dag.py', '--cfg-path', '/tmp/tmph5yyqr3i', '--error-file', '/tmp/tmp5tyqezsx']
[2023-10-01 06:13:01,186] {standard_task_runner.py:77} INFO - Job 637: Subtask thrid_task
[2023-10-01 06:13:01,787] {logging_mixin.py:104} INFO - Running <TaskInstance: our_fourth_dag_v4.thrid_task 2021-10-05T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:13:03,066] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_fourth_dag_v4
AIRFLOW_CTX_TASK_ID=thrid_task
AIRFLOW_CTX_EXECUTION_DATE=2021-10-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-05T00:00:00+00:00
[2023-10-01 06:13:03,068] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:13:03,071] {bash.py:158} INFO - Running command: echo hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 06:13:03,273] {bash.py:169} INFO - Output:
[2023-10-01 06:13:03,339] {bash.py:173} INFO - hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 06:13:03,341] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:13:04,291] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_fourth_dag_v4, task_id=thrid_task, execution_date=20211005T000000, start_date=20231001T061258, end_date=20231001T061304
[2023-10-01 06:13:06,727] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 06:13:06,859] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 4928
[2023-10-01 06:13:07,201] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 06:13:07,202] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-10-01 06:13:07,484] {process_utils.py:66} INFO - Process psutil.Process(pid=4928, status='terminated', exitcode=1, started='06:13:00') (4928) terminated with exit code 1
