[2023-10-01 05:56:59,242] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.thrid_task 2021-08-26T00:00:00+00:00 [queued]>
[2023-10-01 05:57:01,149] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.thrid_task 2021-08-26T00:00:00+00:00 [queued]>
[2023-10-01 05:57:01,800] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 05:57:01,826] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 05:57:01,868] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 05:57:02,999] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): thrid_task> on 2021-08-26T00:00:00+00:00
[2023-10-01 05:57:03,342] {standard_task_runner.py:52} INFO - Started process 2683 to run task
[2023-10-01 05:57:03,800] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_third_dag_v3', 'thrid_task', '2021-08-26T00:00:00+00:00', '--job-id', '237', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_third_dag.py', '--cfg-path', '/tmp/tmpwr4c8gjr', '--error-file', '/tmp/tmpcdef9q00']
[2023-10-01 05:57:03,911] {standard_task_runner.py:77} INFO - Job 237: Subtask thrid_task
[2023-10-01 05:57:04,881] {logging_mixin.py:104} INFO - Running <TaskInstance: our_third_dag_v3.thrid_task 2021-08-26T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 05:57:07,200] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_third_dag_v3
AIRFLOW_CTX_TASK_ID=thrid_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-26T00:00:00+00:00
[2023-10-01 05:57:07,285] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 05:57:07,297] {bash.py:158} INFO - Running command: echo hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 05:57:08,137] {bash.py:169} INFO - Output:
[2023-10-01 05:57:08,227] {bash.py:173} INFO - hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 05:57:08,253] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 05:57:10,252] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_third_dag_v3, task_id=thrid_task, execution_date=20210826T000000, start_date=20231001T055659, end_date=20231001T055710
[2023-10-01 05:57:19,283] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 05:57:20,563] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 2683
[2023-10-01 05:57:22,676] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 05:57:22,738] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-10-01 05:57:23,775] {process_utils.py:66} INFO - Process psutil.Process(pid=2683, status='terminated', exitcode=1, started='05:57:02') (2683) terminated with exit code 1
