[2023-10-01 10:17:59,372] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: postgres_v2.insert_into_table 2021-07-30T00:00:00+00:00 [queued]>
[2023-10-01 10:18:00,430] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: postgres_v2.insert_into_table 2021-07-30T00:00:00+00:00 [queued]>
[2023-10-01 10:18:00,438] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 10:18:00,442] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 10:18:00,472] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 10:18:01,403] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2021-07-30T00:00:00+00:00
[2023-10-01 10:18:01,430] {standard_task_runner.py:52} INFO - Started process 47902 to run task
[2023-10-01 10:18:02,016] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_v2', 'insert_into_table', '2021-07-30T00:00:00+00:00', '--job-id', '2728', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/postgresql_example_2.py', '--cfg-path', '/tmp/tmpk84_q5dm', '--error-file', '/tmp/tmp06ufz_bo']
[2023-10-01 10:18:02,282] {standard_task_runner.py:77} INFO - Job 2728: Subtask insert_into_table
[2023-10-01 10:18:08,534] {logging_mixin.py:104} INFO - Running <TaskInstance: postgres_v2.insert_into_table 2021-07-30T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 10:18:12,633] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=postgres_v2
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2021-07-30T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-30T00:00:00+00:00
[2023-10-01 10:18:12,652] {postgres.py:69} INFO - Executing: 
            insert into dags_run (dt, dag_id) values ('2021-07-30', 'postgres_v2')
        
[2023-10-01 10:18:12,988] {base.py:74} INFO - Using connection to: id: posgres_testing. Host: host.docker.internal, Port: 5432, Schema: testing, Login: airflow, Password: XXXXXXXX, extra: None
[2023-10-01 10:18:13,336] {dbapi.py:180} INFO - Running statement: 
            insert into dags_run (dt, dag_id) values ('2021-07-30', 'postgres_v2')
        , parameters: None
[2023-10-01 10:18:13,371] {dbapi.py:186} INFO - Rows affected: 1
[2023-10-01 10:18:13,510] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=postgres_v2, task_id=insert_into_table, execution_date=20210730T000000, start_date=20231001T101759, end_date=20231001T101813
[2023-10-01 10:18:14,397] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 10:18:15,190] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 47902
[2023-10-01 10:18:25,985] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 10:18:29,330] {process_utils.py:66} INFO - Process psutil.Process(pid=47902, status='terminated', exitcode=1, started='10:18:01') (47902) terminated with exit code 1
