[2023-10-01 04:56:41,803] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.thrid_task 2021-08-02T00:00:00+00:00 [queued]>
[2023-10-01 04:56:51,337] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.thrid_task 2021-08-02T00:00:00+00:00 [queued]>
[2023-10-01 04:56:51,584] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 04:56:51,590] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 04:56:51,594] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 04:56:52,204] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): thrid_task> on 2021-08-02T00:00:00+00:00
[2023-10-01 04:56:52,859] {standard_task_runner.py:52} INFO - Started process 623 to run task
[2023-10-01 04:56:53,721] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v5', 'thrid_task', '2021-08-02T00:00:00+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpbxweal_9', '--error-file', '/tmp/tmptqszbt7f']
[2023-10-01 04:56:54,614] {standard_task_runner.py:77} INFO - Job 3: Subtask thrid_task
[2023-10-01 04:57:13,280] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v5.thrid_task 2021-08-02T00:00:00+00:00 [running]> on host c25e1f8124bc
[2023-10-01 04:57:23,684] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=thrid_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-02T00:00:00+00:00
[2023-10-01 04:57:24,070] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 04:57:24,290] {bash.py:158} INFO - Running command: echo hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 04:57:25,255] {bash.py:169} INFO - Output:
[2023-10-01 04:57:25,275] {bash.py:173} INFO - hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 04:57:25,295] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 04:57:28,374] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=thrid_task, execution_date=20210802T000000, start_date=20231001T045642, end_date=20231001T045728
[2023-10-01 04:57:34,723] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01 04:57:35,468] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 04:57:36,102] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 623
[2023-10-01 04:57:36,164] {process_utils.py:66} INFO - Process psutil.Process(pid=623, status='terminated', exitcode=0, started='04:56:52') (623) terminated with exit code 0
