[2023-10-01 07:59:04,814] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_seventh_dag_v7.get_name 2023-01-18T00:00:00+00:00 [queued]>
[2023-10-01 07:59:05,573] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_seventh_dag_v7.get_name 2023-01-18T00:00:00+00:00 [queued]>
[2023-10-01 07:59:05,591] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 07:59:05,593] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 07:59:05,595] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 07:59:05,868] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): get_name> on 2023-01-18T00:00:00+00:00
[2023-10-01 07:59:05,988] {standard_task_runner.py:52} INFO - Started process 23882 to run task
[2023-10-01 07:59:06,240] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_seventh_dag_v7', 'get_name', '2023-01-18T00:00:00+00:00', '--job-id', '2406', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_seventh_dag.py', '--cfg-path', '/tmp/tmpsk853i9d', '--error-file', '/tmp/tmpwsszgu0d']
[2023-10-01 07:59:06,313] {standard_task_runner.py:77} INFO - Job 2406: Subtask get_name
[2023-10-01 07:59:08,111] {logging_mixin.py:104} INFO - Running <TaskInstance: our_seventh_dag_v7.get_name 2023-01-18T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 07:59:09,174] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_seventh_dag_v7
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-18T00:00:00+00:00
[2023-10-01 07:59:09,821] {python.py:118} INFO - Done. Returned value was: None
[2023-10-01 07:59:09,989] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_seventh_dag_v7, task_id=get_name, execution_date=20230118T000000, start_date=20231001T075904, end_date=20231001T075909
[2023-10-01 07:59:11,822] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-01 07:59:11,891] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 07:59:11,926] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 23882
[2023-10-01 07:59:11,948] {process_utils.py:66} INFO - Process psutil.Process(pid=23882, status='terminated', exitcode=0, started='07:59:05') (23882) terminated with exit code 0
