[2023-10-01 09:52:37,965] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: postgres_v1.create_postgres_connection 2021-08-11T00:00:00+00:00 [queued]>
[2023-10-01 09:52:38,622] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: postgres_v1.create_postgres_connection 2021-08-11T00:00:00+00:00 [queued]>
[2023-10-01 09:52:38,630] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 09:52:38,648] {taskinstance.py:1043} INFO - Starting attempt 5 of 6
[2023-10-01 09:52:38,658] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 09:52:39,062] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_postgres_connection> on 2021-08-11T00:00:00+00:00
[2023-10-01 09:52:39,673] {standard_task_runner.py:52} INFO - Started process 42749 to run task
[2023-10-01 09:52:39,632] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_v1', 'create_postgres_connection', '2021-08-11T00:00:00+00:00', '--job-id', '2609', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/1_postgresql.py', '--cfg-path', '/tmp/tmpjjirnei5', '--error-file', '/tmp/tmpu4nrv85e']
[2023-10-01 09:52:42,123] {standard_task_runner.py:77} INFO - Job 2609: Subtask create_postgres_connection
[2023-10-01 09:52:58,377] {logging_mixin.py:104} INFO - Running <TaskInstance: postgres_v1.create_postgres_connection 2021-08-11T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 09:53:00,190] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=postgres_v1
AIRFLOW_CTX_TASK_ID=create_postgres_connection
AIRFLOW_CTX_EXECUTION_DATE=2021-08-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-11T00:00:00+00:00
[2023-10-01 09:53:00,559] {postgres.py:69} INFO - Executing: create table if not exists dags_run(
        dt  date,
        dag_id character varying,
        primary key (dt,dag_id)
        )
[2023-10-01 09:53:00,703] {base.py:74} INFO - Using connection to: id: posgres_testing. Host: host.docker.internal, Port: 5432, Schema: testing, Login: airflow, Password: XXXXXXXX, extra: None
[2023-10-01 09:53:01,039] {dbapi.py:180} INFO - Running statement: create table if not exists dags_run(
        dt  date,
        dag_id character varying,
        primary key (dt,dag_id)
        ), parameters: None
[2023-10-01 09:53:01,097] {dbapi.py:186} INFO - Rows affected: -1
[2023-10-01 09:53:01,124] {postgres.py:73} INFO - NOTICE:  relation "dags_run" already exists, skipping

[2023-10-01 09:53:02,223] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=postgres_v1, task_id=create_postgres_connection, execution_date=20210811T000000, start_date=20231001T095238, end_date=20231001T095302
[2023-10-01 09:53:08,564] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01 09:53:08,831] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 09:53:09,315] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 42749
[2023-10-01 09:53:09,732] {process_utils.py:66} INFO - Process psutil.Process(pid=42749, status='terminated', exitcode=0, started='09:52:38') (42749) terminated with exit code 0
