[2023-10-01 06:19:30,329] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.second_task 2022-01-01T00:00:00+00:00 [queued]>
[2023-10-01 06:19:30,844] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.second_task 2022-01-01T00:00:00+00:00 [queued]>
[2023-10-01 06:19:30,889] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:19:30,891] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:19:30,898] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:19:31,334] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2022-01-01T00:00:00+00:00
[2023-10-01 06:19:31,418] {standard_task_runner.py:52} INFO - Started process 6246 to run task
[2023-10-01 06:19:31,527] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_fourth_dag_v4', 'second_task', '2022-01-01T00:00:00+00:00', '--job-id', '903', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_fourth_dag.py', '--cfg-path', '/tmp/tmpccp5q2k7', '--error-file', '/tmp/tmpq2smdrwt']
[2023-10-01 06:19:31,694] {standard_task_runner.py:77} INFO - Job 903: Subtask second_task
[2023-10-01 06:19:32,731] {logging_mixin.py:104} INFO - Running <TaskInstance: our_fourth_dag_v4.second_task 2022-01-01T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:19:33,613] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_fourth_dag_v4
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-01T00:00:00+00:00
[2023-10-01 06:19:33,624] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:19:33,631] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2023-10-01 06:19:33,855] {bash.py:169} INFO - Output:
[2023-10-01 06:19:33,894] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2023-10-01 06:19:33,921] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:19:34,570] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_fourth_dag_v4, task_id=second_task, execution_date=20220101T000000, start_date=20231001T061930, end_date=20231001T061934
[2023-10-01 06:19:35,527] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01 06:19:35,766] {local_task_job.py:146} INFO - Task exited with return code 0
