[2023-10-01 06:14:55,296] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.thrid_task 2021-10-24T00:00:00+00:00 [queued]>
[2023-10-01 06:14:55,756] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.thrid_task 2021-10-24T00:00:00+00:00 [queued]>
[2023-10-01 06:14:55,758] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:14:55,760] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:14:55,762] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:14:55,960] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): thrid_task> on 2021-10-24T00:00:00+00:00
[2023-10-01 06:14:56,098] {standard_task_runner.py:52} INFO - Started process 5255 to run task
[2023-10-01 06:14:56,322] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_fourth_dag_v4', 'thrid_task', '2021-10-24T00:00:00+00:00', '--job-id', '696', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_fourth_dag.py', '--cfg-path', '/tmp/tmpmn4zdn9l', '--error-file', '/tmp/tmpt78hmj5q']
[2023-10-01 06:14:56,405] {standard_task_runner.py:77} INFO - Job 696: Subtask thrid_task
[2023-10-01 06:14:58,860] {logging_mixin.py:104} INFO - Running <TaskInstance: our_fourth_dag_v4.thrid_task 2021-10-24T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:14:59,834] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_fourth_dag_v4
AIRFLOW_CTX_TASK_ID=thrid_task
AIRFLOW_CTX_EXECUTION_DATE=2021-10-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-24T00:00:00+00:00
[2023-10-01 06:14:59,848] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:14:59,878] {bash.py:158} INFO - Running command: echo hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 06:15:00,309] {bash.py:169} INFO - Output:
[2023-10-01 06:15:00,332] {bash.py:173} INFO - hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 06:15:00,361] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:15:00,707] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_fourth_dag_v4, task_id=thrid_task, execution_date=20211024T000000, start_date=20231001T061455, end_date=20231001T061500
[2023-10-01 06:15:02,148] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01 06:15:02,538] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 06:15:03,519] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 5255
[2023-10-01 06:15:03,554] {process_utils.py:66} INFO - Process psutil.Process(pid=5255, status='terminated', exitcode=0, started='06:14:55') (5255) terminated with exit code 0
