[2023-10-01 06:16:05,380] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.second_task 2021-11-11T00:00:00+00:00 [queued]>
[2023-10-01 06:16:05,846] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.second_task 2021-11-11T00:00:00+00:00 [queued]>
[2023-10-01 06:16:05,859] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:16:05,879] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:16:05,884] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:16:12,987] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2021-11-11T00:00:00+00:00
[2023-10-01 06:16:13,756] {standard_task_runner.py:52} INFO - Started process 5512 to run task
[2023-10-01 06:16:14,085] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_fourth_dag_v4', 'second_task', '2021-11-11T00:00:00+00:00', '--job-id', '749', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_fourth_dag.py', '--cfg-path', '/tmp/tmpc4795w_a', '--error-file', '/tmp/tmp1wiagc6e']
[2023-10-01 06:16:14,430] {standard_task_runner.py:77} INFO - Job 749: Subtask second_task
[2023-10-01 06:16:18,393] {logging_mixin.py:104} INFO - Running <TaskInstance: our_fourth_dag_v4.second_task 2021-11-11T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:16:20,136] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_fourth_dag_v4
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-11-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-11T00:00:00+00:00
[2023-10-01 06:16:20,171] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:16:20,181] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2023-10-01 06:16:20,870] {bash.py:169} INFO - Output:
[2023-10-01 06:16:20,925] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2023-10-01 06:16:20,963] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:16:21,499] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_fourth_dag_v4, task_id=second_task, execution_date=20211111T000000, start_date=20231001T061605, end_date=20231001T061621
[2023-10-01 06:16:24,694] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01 06:16:26,482] {local_task_job.py:146} INFO - Task exited with return code 0
