[2023-10-01 10:07:22,459] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: postgres_v1.insert_into_table 2021-09-03T00:00:00+00:00 [queued]>
[2023-10-01 10:07:22,838] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: postgres_v1.insert_into_table 2021-09-03T00:00:00+00:00 [queued]>
[2023-10-01 10:07:22,855] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 10:07:22,860] {taskinstance.py:1043} INFO - Starting attempt 4 of 6
[2023-10-01 10:07:22,868] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 10:07:23,376] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2021-09-03T00:00:00+00:00
[2023-10-01 10:07:23,413] {standard_task_runner.py:52} INFO - Started process 45984 to run task
[2023-10-01 10:07:23,824] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_v1', 'insert_into_table', '2021-09-03T00:00:00+00:00', '--job-id', '2699', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/1_postgresql.py', '--cfg-path', '/tmp/tmprs13x_ln', '--error-file', '/tmp/tmpakygqtcd']
[2023-10-01 10:07:23,995] {standard_task_runner.py:77} INFO - Job 2699: Subtask insert_into_table
[2023-10-01 10:07:25,964] {logging_mixin.py:104} INFO - Running <TaskInstance: postgres_v1.insert_into_table 2021-09-03T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 10:07:33,972] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=postgres_v1
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2021-09-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-03T00:00:00+00:00
[2023-10-01 10:07:34,675] {postgres.py:69} INFO - Executing: 
            insert into dags_run (dt, dag_id) values ('2021-09-03', 'postgres_v1')
        
[2023-10-01 10:07:37,623] {base.py:74} INFO - Using connection to: id: posgres_testing. Host: host.docker.internal, Port: 5432, Schema: testing, Login: airflow, Password: XXXXXXXX, extra: None
[2023-10-01 10:07:37,935] {dbapi.py:180} INFO - Running statement: 
            insert into dags_run (dt, dag_id) values ('2021-09-03', 'postgres_v1')
        , parameters: None
[2023-10-01 10:07:38,046] {dbapi.py:186} INFO - Rows affected: 1
[2023-10-01 10:07:38,699] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=postgres_v1, task_id=insert_into_table, execution_date=20210903T000000, start_date=20231001T100722, end_date=20231001T100738
[2023-10-01 10:07:41,804] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01 10:07:42,116] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 10:07:42,217] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 45984
[2023-10-01 10:07:42,255] {process_utils.py:66} INFO - Process psutil.Process(pid=45984, status='terminated', exitcode=0, started='10:07:22') (45984) terminated with exit code 0
