[2023-10-01 10:18:21,146] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: postgres_v2.delete_data_from_table 2021-08-11T00:00:00+00:00 [queued]>
[2023-10-01 10:18:22,749] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: postgres_v2.delete_data_from_table 2021-08-11T00:00:00+00:00 [queued]>
[2023-10-01 10:18:22,751] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 10:18:22,754] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 10:18:22,760] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 10:18:23,316] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2021-08-11T00:00:00+00:00
[2023-10-01 10:18:23,411] {standard_task_runner.py:52} INFO - Started process 47927 to run task
[2023-10-01 10:18:23,655] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_v2', 'delete_data_from_table', '2021-08-11T00:00:00+00:00', '--job-id', '2735', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/postgresql_example_2.py', '--cfg-path', '/tmp/tmpqvtlz87n', '--error-file', '/tmp/tmpqri5q9p1']
[2023-10-01 10:18:23,837] {standard_task_runner.py:77} INFO - Job 2735: Subtask delete_data_from_table
[2023-10-01 10:18:25,331] {logging_mixin.py:104} INFO - Running <TaskInstance: postgres_v2.delete_data_from_table 2021-08-11T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 10:18:29,846] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=postgres_v2
AIRFLOW_CTX_TASK_ID=delete_data_from_table
AIRFLOW_CTX_EXECUTION_DATE=2021-08-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-11T00:00:00+00:00
[2023-10-01 10:18:29,912] {postgres.py:69} INFO - Executing: 
            delete from dags_run where dt = '2021-08-11' and dag_id = 'postgres_v2';
        
[2023-10-01 10:18:30,603] {base.py:74} INFO - Using connection to: id: posgres_testing. Host: host.docker.internal, Port: 5432, Schema: testing, Login: airflow, Password: XXXXXXXX, extra: None
[2023-10-01 10:18:31,059] {dbapi.py:180} INFO - Running statement: 
            delete from dags_run where dt = '2021-08-11' and dag_id = 'postgres_v2';
        , parameters: None
[2023-10-01 10:18:31,120] {dbapi.py:186} INFO - Rows affected: 0
[2023-10-01 10:18:31,637] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=postgres_v2, task_id=delete_data_from_table, execution_date=20210811T000000, start_date=20231001T101821, end_date=20231001T101831
[2023-10-01 10:18:39,397] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 10:18:39,530] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 47927
[2023-10-01 10:18:39,765] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 10:18:40,198] {process_utils.py:66} INFO - Process psutil.Process(pid=47927, status='terminated', exitcode=1, started='10:18:23') (47927) terminated with exit code 1
